name: .NET tests

# runs on every push on every branch
on:
  push:
    paths-ignore: 
      - '**.md'
      - '**.txt'


jobs:

  test:
    runs-on: 'ubuntu-latest'
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-restore --configuration Release --logger "console;verbosity=detailed"

