name: .NET PR tests

# runs only on pull requests
on:
  pull_request:
    branches: 
      - 'master'
      - 'rel/**'
      - 'dev/**'
    paths-ignore: 
      - '**.md'
      - '**.txt'
      - '**.png'

  
jobs:

  prtest:
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest','windows-latest']

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-restore --configuration Release --logger "console;verbosity=detailed"

