name: Publish on Nuget

on:
  release:
    types:
      - published

jobs:
  release:
    
    runs-on: ubuntu-latest

    steps:

    # setup
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    # build and verify tests. 
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    # get version
    - name: Extract version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      
    # pack and publish
    - name: Pack
      run: dotnet pack StackInjector --configuration Release -p:PackageVersion=$RELEASE_VERSION
    - name: Push
      run: dotnet nuget push "StackInjector/bin/Release/StackInjector.$RELEASE_VERSION.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
